- product/src/main/java/com/yas/product/controller/ProductController.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/viewmodel/ProductThumbnailGetVm.java
- storefront/common/components/Layout.tsx
- storefront/modules/catalog/models/ProductThumbnail.ts
- storefront/modules/catalog/services/ProductService.ts
- storefront/pages/_app.tsx
- storefront/pages/index.tsx
- storefront/styles/globals.css
- Old UI
-New UI:
- Add animation when hover and instead of click on "More detail" button. Now we just click on the product
https://user-images.githubusercontent.com/103627485/196842807-61a37d18-870d-4c78-af7b-003c57b413e9.mp4
- Add product price
> enhance homepage UI and add price attribute to product info

- backoffice-bff/pom.xml
* Change the version of spring boot to `3.0.2`
* Change the version of spring cloud to `2022.0.1` for compatible with spring boot v3
* <b>Unexpected change: </b>  when changing version of the spring cloud then it leads to incompatibility with Spring Cloud Sleuth, so I must change the package from `org.springframework.cloud.sleuth` to `io.micrometer.tracing` 
<i>Application give an error:</i>
And here is the migration guide: https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide
All function work as expected:
!
[image](https://user-images.githubusercontent.com/101847895/216799508-491c9e91-ca25-435e-8c63-0c42ef6af9dd.png)
> [backoffice-bff] Upgrade spring boot to v3

- backoffice-bff/src/main/java/com/yas/backofficebff/config/SecurityConfig.java
- cart/src/main/java/com/yas/cart/config/SecurityConfig.java
- customer/src/main/java/com/yas/customer/config/SecurityConfig.java
- inventory/src/main/java/com/yas/inventory/config/SecurityConfig.java
- location/src/main/java/com/yas/location/config/SecurityConfig.java
- media/src/main/java/com/yas/media/config/SecurityConfig.java
- order/src/main/java/com/yas/order/config/SecurityConfig.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/config/SecurityConfig.java
- payment/src/main/java/com/yas/payment/config/SecurityConfig.java
- product/src/main/java/com/yas/product/config/SecurityConfig.java
- promotion/src/main/java/com/yas/promotion/config/SecurityConfig.java
- rating/src/main/java/com/yas/rating/config/SecurityConfig.java
- search/src/main/java/com/yas/search/config/SecurityConfig.java
- tax/src/main/java/com/yas/tax/config/SecurityConfig.java
When YAS applications deploy to k8s cluster environment, the k8s need to check liveness and readiness on the pods, however the 401 error occur when check liveness and readiness, so YAS applications need open urls actuator
> Config security allow access actuator without permission

- storefront/.env.development
- storefront/.env.production
- storefront/modules/catalog/services/ProductService.ts
- storefront/modules/order/services/OrderService.ts
When deploy to k8s environment the storefront application must change the NEXT_PUBLIC_API_BASE_PATH to another value, however the environment consist NEXT_PUBLIC  prefix that mean it is browser environment and cannot change when runtime,
and I saw only a function use this variable to fetch data on server side
https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables
> Change browser environment to server environment nexjs

- search/src/main/java/com/yas/search/config/ElasticsearchDataConfig.java
- search/src/main/java/com/yas/search/config/ImperativeClientConfig.java
- search/src/main/resources/application.properties
On the elasticsearch server installing k8s require username and password when establish connection, however the search application lack of config for username and password
> Add username and password for elasticsearch client configuration

- backoffice-bff/Dockerfile
- cart/Dockerfile
- customer/Dockerfile
- inventory/Dockerfile
- location/Dockerfile
- media/Dockerfile
- order/Dockerfile
- payment/Dockerfile
- product/Dockerfile
- promotion/Dockerfile
- rating/Dockerfile
- search/Dockerfile
- storefront-bff/Dockerfile
- tax/Dockerfile
From the last changing, the output jar version was updated by parent version, and these version can be changed any time. But the dockerfile is using the fixing version, that is the cause of deploy fail. To fix that, all the dockerfile using jar will the command copy with `*` to the target jar to app.jar and run with that name.
> YAS-0002 fix docker build with versioning

- cart/src/main/java/com/yas/cart/exception/ApiExceptionHandler.java
- customer/src/main/java/com/yas/customer/exception/ApiExceptionHandler.java
- inventory/src/main/java/com/yas/inventory/exception/ApiExceptionHandler.java
- location/src/main/java/com/yas/location/exception/ApiExceptionHandler.java
- media/src/main/java/com/yas/media/exception/ControllerAdvisor.java
- order/src/main/java/com/yas/order/exception/ApiExceptionHandler.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/exception/ApiExceptionHandler.java
- payment/src/main/java/com/yas/payment/exception/ApiExceptionHandler.java
- product/src/main/java/com/yas/product/exception/ApiExceptionHandler.java
- promotion/src/main/java/com/yas/promotion/exception/ApiExceptionHandler.java
- rating/src/main/java/com/yas/rating/exception/ApiExceptionHandler.java
- search/src/main/java/com/yas/search/exception/ApiExceptionHandler.java
- tax/src/main/java/com/yas/tax/exception/ApiExceptionHandler.java
add @ExceptionHandler(Exception.class) to handle other exceptions.
> #763 ApiExceptionHandler - Missing handling generic, 500 error

- identity/realm-export.json
Turn of "Client authentication" for swagger ui client registration in keycloak
> Turn of "Client authentication" for swagger ui client registration in keycloak

- .github/workflows/backoffice-bff-ci.yaml
- .github/workflows/cart-ci.yaml
- .github/workflows/customer-ci.yaml
- .github/workflows/inventory-ci.yaml
- .github/workflows/location-ci.yaml
- .github/workflows/media-ci.yaml
- .github/workflows/order-ci.yaml
- .github/workflows/payment-ci.yaml
- .github/workflows/payment-paypal-ci.yaml
- .github/workflows/product-ci.yaml
- .github/workflows/promotion-ci.yaml
- .github/workflows/rating-ci.yaml
- .github/workflows/sampledata-ci.yaml
- .github/workflows/search-ci.yaml
- .github/workflows/storefront-bff-ci.yaml
- .github/workflows/tax-ci.yaml
- .github/workflows/webhook-ci.yaml
- pom.xml
- tax/src/it/resources/application.properties
- Remove the unnecessary integration test profile (We will be using the same profile as the unit test)
- Run integration tests during the integration test phase of the maven build cycle (`failsafe` plugin default behavior)
- Run `jacoco` `report` in verify phase (after integration test) so that it can also collect the integration test results for the coverage report
- Config ci for all service to:
- Run `mvn verify`, which includes `test` phase (which contains the tests)
- Run the `verify` step, which is more costly, after the `checkstyle` step in order to reduce the pipelines run time in case `checkstyle` fail
- Reconfigurate the test reports collectors to includes `failsafe` reports
> #940 #941 #942 config ci flows ii jacoco

- backoffice/pages/location/state-or-provinces/index.tsx
- location/src/main/java/com/yas/location/repository/StateOrProvinceRepository.java
- location/src/main/java/com/yas/location/service/StateOrProvinceService.java
- The create or update function will now verify the name ignore case of the state or province within that specific country, rather than across all countries.
- In the backoffice, the stateOrProvince ID display has been removed from the StateOrProvince section as it was deemed unnecessary.
- Refactor to sort by the name of the StateOrProvince by default, previously sorted by ID.
> [Location] Refactor create and update state-or-province:

- product/src/it/java/com/yas/product/config/AbstractControllerIT.java
- product/src/it/java/com/yas/product/config/IntegrationTestConfiguration.java
- product/src/it/java/com/yas/product/controller/BrandControllerIT.java
- product/src/it/java/com/yas/product/controller/CategoryControllerIT.java
- product/src/it/java/com/yas/product/service/MediaServiceIT.java
- product/src/it/resources/application.properties
- product/src/it/resources/test-realm.json
- product/src/main/java/com/yas/product/controller/BrandController.java
- product/src/main/java/com/yas/product/exception/BadRequestException.java
- product/src/main/java/com/yas/product/service/BrandService.java
- product/src/test/java/com/yas/product/service/CategoryServiceTest.java
- I apply integration test for brand and category inside product module.
- The remaining services within the product will be included in a separate PR to keep the code concise.
> [Product - Test] Category and Brand integration test

- product/src/it/java/com/yas/product/service/ProductServiceIT.java
- product/src/main/java/com/yas/product/repository/ProductOptionCombinationRepository.java
- product/src/main/java/com/yas/product/repository/ProductOptionValueRepository.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/test/java/com/yas/product/service/ProductAttributeGroupServiceTest.java
- product/src/test/java/com/yas/product/service/ProductAttributeServiceTest.java
- product/src/test/java/com/yas/product/service/ProductOptionServiceTest.java
#1064 [BACKOFFICE] [Bugs] Product Variations - delete variant
> #1064 [BACKOFFICE] [Bugs] Product Variations - delete variant

- backoffice/modules/catalog/components/ProductVariation.tsx
- backoffice/modules/catalog/models/FormProduct.ts
- backoffice/modules/catalog/models/ProductPayload.ts
- Create function to build correct productOptionValues object before request.
- Remove productOptions from FormProduct, this variable could cause problem when delete variations, both in FE and BE, as it is a standalone variable from productVariations, which will make options persisted even though product variations have been deleted.
- Check empty option value(s), any option should not have empty value like this:
> Fix model mismatch in backoffice and product service

- storefront/common/components/ProductImageGallery.tsx
- storefront/modules/catalog/components/ProductDetails.tsx
#1064 [BACKOFFICE] [Bugs] Product Variations - show images with thumbnail
> #1064 [BACKOFFICE] [Bugs] Product Variations - show images with thumbnail

- search/src/it/java/com/yas/search/config/IntegrationTestConfiguration.java
- search/src/it/java/com/yas/search/controller/ProductControllerIT.java
- search/src/main/java/com/yas/search/service/ProductService.java
- search/src/test/java/com/yas/search/service/ProductServiceTest.java
Product filter on search now works as expected. For example:
- If customers selects 'Phone' in category field and 'Apple' in brand field, search page will only return products with both attributes.
- If customers selects both 'Phone' and 'Laptop' in category field, search page will return products classified as either Phone or Laptop.
**From:**
**To:**
> #1112[Search] Re-configure search filter

- order/src/main/java/com/yas/order/mapper/CheckoutMapper.java
- order/src/main/java/com/yas/order/model/Checkout.java
- order/src/main/java/com/yas/order/model/CheckoutItem.java
- order/src/main/java/com/yas/order/model/Order.java
- order/src/main/java/com/yas/order/model/OrderItem.java
- order/src/main/java/com/yas/order/repository/CheckoutItemRepository.java
- order/src/main/java/com/yas/order/service/CheckoutService.java
- order/src/main/java/com/yas/order/viewmodel/checkout/CheckoutItemPostVm.java
- order/src/main/resources/db/changelog/ddl/changelog-0015.sql
- order/src/test/java/com/yas/order/controller/CheckoutControllerTest.java
- order/src/test/java/com/yas/order/mapper/CheckoutMapperTest.java
- order/src/test/java/com/yas/order/service/CheckoutServiceTest.java
- order/src/test/java/com/yas/order/utils/SecurityContextUtils.java
- payment/src/main/java/com/yas/payment/model/Payment.java
- payment/src/main/resources/db/changelog/ddl/changelog-0003.sql
[OrderRefactor] Update the order, checkout, and payment tables according to the design #1198
> #1198-update-the-order-checkout-payment-tables

- common-library/src/main/java/com/yas/commonlibrary/kafka/cdc/BaseCdcConsumer.java
- recommendation/src/main/java/com/yas/recommendation/kafka/consumer/ProductSyncService.java
- search/src/it/java/com/yas/search/kafka/ProductCdcConsumerTest.java
- search/src/main/java/com/yas/search/kafka/consumer/ProductSyncDataConsumer.java
- search/src/test/java/com/yas/search/consumer/ProductSyncDataConsumerTest.java
This PR is to:
- **Kafka Consumer Configuration:** Define **Kafka Consumer** config to be able to deserialize message to target object (base configuration class `BaseKafkaListenerConfig`, see `ProductCdcKafkaListenerConfig`).
- **Message Validation:** Define configuration for message validation.
- **Non-Blocking Retries with Dead-Letter Queue:** Enables non-blocking retries, including a dead-letter queue, for Kafka Consumers when errors occur (using `@RetryableTopic`).
- **Base Structure for CDC Kafka Consumer:** Create base structure for CDC Kafka Consumer, `BaseKafkaListenerConfig<T>`, `BaseCdcConsumer<T>`, `@RetrySupportDql` (`T` is message type).
- Apply these changes to `search`, `recommendation` module.
>**_Note:_** above changes use for CDC Consumer only. We need to do more tests …
> #1148 - Enhance Error Handler, Serialize, Deserialize

- docker/grafana/provisioning/dashboards/observability_dashboard.json
Replaced old HTTP metrics panels with the following panels:
- **Total HTTP Requests:** Displays the total number of requests served during the selected time range, which can be adjusted using the time picker in the upper-right corner of the dashboard.
- **HTTP Request Status Codes Ratio**: Displays the percentage distribution of different HTTP status codes.
- **HTTP Requests Per Second:** Displays the number of requests served per second, separated by endpoint.
- **HTTP Request Count:** Displays the count of successful and failed requests, separated by endpoint.
- **Average HTTP Request Duration:** Displays the average request duration, separated by endpoint.
> #1115 Enhance grafana http metrics panels

- backoffice-bff/src/main/java/com/yas/backofficebff/Application.java
- cart/src/test/java/com/yas/cart/controller/CartItemControllerTest.java
- common-library/src/test/resources/test-realm.json
- customer/src/main/java/com/yas/customer/service/CustomerService.java
- customer/src/test/java/com/yas/customer/service/CustomerServiceTest.java
- docker-compose.yml
- media/src/it/java/com/yas/media/controller/MediaControllerIT.java
- pom.xml
- storefront-bff/src/main/java/com/yas/storefrontbff/StorefrontBffApplication.java
[#1234 - Update dependencies to recent latest version](https://github.com/nashtech-garage/yas/issues/1234)
> #1234 - Update dependencies to recent latest version

- backoffice/modules/catalog/components/ProductGeneralInformation.tsx
> Add validate vs dirty check to price field

- storefront/pages/products/[slug].tsx
> Handle error when fetching the get-average-star API on Product Detail page

- common-library/src/it/java/common/kafka/CdcConsumerTest.java
- common-library/src/main/java/com/yas/commonlibrary/kafka/cdc/BaseCdcConsumer.java
- common-library/src/main/java/com/yas/commonlibrary/kafka/cdc/config/BaseKafkaListenerConfig.java
- common-library/src/main/java/com/yas/commonlibrary/kafka/cdc/message/ProductMsgKey.java
- docker-compose.yml
- recommendation/src/main/java/com/yas/recommendation/configuration/EmbeddingSearchConfiguration.java
- recommendation/src/main/java/com/yas/recommendation/kafka/config/consumer/ProductCdcKafkaListenerConfig.java
- recommendation/src/main/java/com/yas/recommendation/kafka/consumer/ProductSyncDataConsumer.java
- recommendation/src/main/java/com/yas/recommendation/kafka/consumer/ProductSyncService.java
- recommendation/src/main/java/com/yas/recommendation/vector/product/service/ProductVectorSyncService.java
- recommendation/src/main/resources/application.properties
- search/src/it/java/com/yas/search/kafka/ProductCdcConsumerTest.java
- search/src/it/resources/application.properties
- search/src/main/java/com/yas/search/kafka/config/consumer/ProductCdcKafkaListenerConfig.java
- search/src/main/java/com/yas/search/kafka/consumer/ProductSyncDataConsumer.java
- search/src/main/java/com/yas/search/service/ProductSyncDataService.java
- search/src/main/resources/application.properties
- search/src/test/java/com/yas/search/consumer/ProductSyncDataConsumerTest.java
- search/src/test/java/com/yas/search/service/ProductSyncDataServiceTest.java
- Support ser/de CDC message key.
- Update product sync services to handle hard delete in case.
- Add kafka-ui image.
> #1227 - Handling hard delete data from Sample Data
