- README.md
- Need someone to verify the docs
> Getting started with Docker in Ubuntu

- .github/workflows/storefront-ci.yaml
- storefront/sonar-project.properties
run sonar on main, internal pull requests
> [storefront] run build on every changes

- product/src/main/java/com/yas/product/controller/CategoryController.java
- product/src/test/java/com/yas/product/controller/CategoryControllerTest.java
unit test when getting valid categories successfully
unit test when getting a valid category 
unit test when getting a category with not found Id
> T41 add Unit test for get category list and get detail category

- product/src/main/java/com/yas/product/controller/ProductAttributeController.java
- product/src/main/java/com/yas/product/viewmodel/ProductAttributeGetVm.java
- product/src/test/java/com/yas/product/controller/ProductAttributeControllerTest.java
> Unit test Product Attribute Controller version 1.0

- backoffice/modules/catalog/models/ProductPost.ts
- backoffice/modules/catalog/services/ProductService.ts
- backoffice/pages/catalog/products/create.tsx
- product/src/main/java/com/yas/product/controller/ProductController.java
- product/src/main/java/com/yas/product/model/Product.java
- product/src/main/java/com/yas/product/model/ProductImage.java
- product/src/main/java/com/yas/product/repository/ProductImageRepository.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/viewmodel/ProductPostVm.java
- product/src/test/java/com/yas/product/service/ProductServiceTest.java
>  done create new product

- backoffice/modules/catalog/models/Products.ts
- backoffice/modules/catalog/services/ProductService.ts
- backoffice/package-lock.json
- backoffice/package.json
- backoffice/pages/catalog/products/index.tsx
- backoffice/styles/globals.css
- product/src/main/java/com/yas/product/controller/ProductController.java
- product/src/main/java/com/yas/product/repository/ProductRepository.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/viewmodel/ProductListGetVm.java
- product/src/test/java/com/yas/product/service/ProductServiceTest.java
Complete paginate product list, the default number of item each page is 5 items
The pointer is disabled automatically on "Next" or "Previous" button  when the current page is the first or last page
This include unit test with 100% line coverage of its method
> #78 paginate products

- backoffice/modules/catalog/models/Product.ts
- backoffice/modules/catalog/models/ProductPut.ts
- backoffice/modules/catalog/services/ProductService.ts
- backoffice/pages/catalog/products/[id]/edit.tsx
- product/src/main/java/com/yas/product/model/Category.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/viewmodel/ProductDetailVm.java
- product/src/main/java/com/yas/product/viewmodel/ProductPutVm.java
- product/src/test/java/com/yas/product/service/ProductServiceTest.java
**Before update - show detail:**
**After update(change brand, isPublished, isFeatured, category, thumbnail, images) - redirect products page:**
> Update update product function: Add Brand, Category Selected Box, Product Images, Price, IsAllowedOrder, isPublished, isFeatured

- product/src/main/java/com/yas/product/model/Category.java
Add Json Ignore to prevent infinity loop.
> Update Category, add JsonIgnore

- backoffice/pages/catalog/products/[id]/edit.tsx
Update Product - Fixed Load Product Detail Failed When Category Null, Images Null
> Update Product - Fixed Load Product Detail Failed When Product Category, Images Null

- backoffice/modules/catalog/models/ProductAttributeValue.ts
- backoffice/modules/catalog/models/ProductAttributeValuePost.ts
- backoffice/modules/catalog/services/ProductAttributeValueService.ts
- backoffice/pages/catalog/products/[id]/edit.tsx
- backoffice/pages/catalog/products/[id]/productAttributes.tsx
- product/src/main/java/com/yas/product/controller/ProductAttributeValueController.java
- product/src/main/java/com/yas/product/viewmodel/ProductAttributeValuePostVm.java
- product/src/test/java/com/yas/product/controller/ProductAttributeValueControllerTest.java
https://user-images.githubusercontent.com/64051785/192928326-a3279d9b-d64e-4e55-b628-1742498c6b2d.mp4
> UI Add Product Attribute to Product

- backoffice/modules/catalog/services/CategoryService.ts
- backoffice/pages/catalog/categories/index.tsx
- product/src/main/java/com/yas/product/controller/CategoryController.java
[back office & product] delete category
> API and UI delete category

- customer/src/main/java/com/yas/customer/config/KeycloakClientConfig.java
- customer/src/main/java/com/yas/customer/config/SecurityConfig.java
- customer/src/main/java/com/yas/customer/controller/CustomerController.java
- customer/src/main/java/com/yas/customer/exception/ApiExceptionHandler.java
- customer/src/main/java/com/yas/customer/exception/CreateGuestUserException.java
- customer/src/main/java/com/yas/customer/exception/InternalErrorException.java
- customer/src/main/java/com/yas/customer/service/CustomerService.java
- customer/src/main/java/com/yas/customer/viewmodel/GuestUserVm.java
issue #119 
creeate API That call Keycloak to add new user with:
- role 'GUEST'
- username (random 12 char) + '_guest@yas.com'
- password hardcoded 'GUEST'
> create guest user

- backoffice-bff/src/main/resources/application.yaml
- media/src/main/java/com/yas/media/controller/MediaController.java
- product/src/main/java/com/yas/product/service/MediaService.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/viewmodel/ProductPutVm.java
- product/src/test/java/com/yas/product/service/ProductServiceTest.java
**Before update product:**
**Start update product:**
**After update product, media will be deleted in database:**
> T142 -  Recode update product function, delete media when update

- backoffice/modules/catalog/models/Category.ts
- backoffice/pages/catalog/categories/[id]/edit.tsx
- backoffice/pages/catalog/categories/create.tsx
- backoffice/pages/catalog/products/index.tsx
- product/src/main/java/com/yas/product/viewmodel/CategoryGetVm.java
- product/src/test/java/com/yas/product/controller/CategoryControllerTest.java
> remove redundant attribute, add hierarchy category when create and edit category

- cart/src/main/java/com/yas/cart/controller/CartController.java
- cart/src/main/java/com/yas/cart/service/CartService.java
> update cart API

- product/src/main/java/com/yas/product/controller/ProductOptionValueController.java
- product/src/main/java/com/yas/product/repository/ProductOptionValueRepository.java
- product/src/main/java/com/yas/product/viewmodel/ProductOptionValueGetVm.java
- product/src/main/java/com/yas/product/viewmodel/ProductOptionValuePostVm.java
- product/src/test/java/com/yas/product/controller/ProductOptionValueControllerTest.java
> Rest Api and Unit test

- backoffice/common/components/Layout.tsx
- backoffice/common/items/ListGroup.tsx
- backoffice/package-lock.json
- backoffice/package.json
- backoffice/pages/_app.tsx
Each child in a list should have a unique "key" prop; Do not add stylesheets using next/head
> [backoffice] fix warning

- backoffice/modules/catalog/models/ProductThumbnail.ts
- backoffice/modules/catalog/models/ProductThumbnails.ts
- backoffice/modules/catalog/services/CategoryService.ts
- backoffice/pages/catalog/categories/[id]/edit.tsx
- backoffice/pages/catalog/categories/[id]/index.tsx
- backoffice/pages/catalog/categories/[id]/listProduct.tsx
- backoffice/pages/catalog/categories/index.tsx
- product/src/main/java/com/yas/product/controller/ProductController.java
> View list Product from Category and custom UI Edit category

- cart/src/main/java/com/yas/cart/service/CartService.java
- storefront-bff/src/main/java/com/yas/storefrontbff/filter/GuestAuthenticationFilter.java
- storefront/modules/cart/services/CartService.ts
> [storefront-bff] get cart

- storefront/common/components/Layout.tsx
- storefront/package-lock.json
- storefront/package.json
- storefront/pages/_app.tsx
- storefront/pages/cart/index.tsx
- storefront/styles/cart.css
UI for list cart item when user click shopping cart icon in the header.
https://user-images.githubusercontent.com/103627485/195494223-2a45b37d-1b3b-4d00-aee3-0075cfd33c29.mp4
This  is video demo. Note that the data there is fake data cause the server-side's handler still not completed yet (get user cart).
> 185 cart UI

- backoffice/modules/catalog/services/BrandService.ts
- backoffice/pages/catalog/brands/[id]/edit.tsx
- backoffice/pages/catalog/brands/index.tsx
> edit brand feature

- storefront/common/components/AuthenticationInfo.tsx
Move fecth move-cart api to callback function of getAuthenticationInfo()
> Refactor AuthenticationInfo.tsx

- custom_proxy_settings.conf
- docker-compose.yml
> Fix limit body size

- backoffice/modules/catalog/components/ProductVariation.tsx
fix no images of product variation
> fix-create-product

- backoffice/styles/common/app.css
- product/src/main/java/com/yas/product/controller/ProductOptionValueController.java
- product/src/main/java/com/yas/product/viewmodel/ProductVariationVm.java
- product/src/test/java/com/yas/product/controller/ProductOptionValueControllerTest.java
- storefront/modules/catalog/models/ProductOptionValueGet.ts
- storefront/modules/catalog/models/ProductVariations.ts
- storefront/modules/catalog/services/ProductService.ts
- storefront/pages/products/[slug].tsx
Fetch from be and render on fe
> Product variation view

- product/src/main/java/com/yas/product/controller/CategoryController.java
- product/src/main/java/com/yas/product/exception/BadRequestException.java
- product/src/main/java/com/yas/product/exception/NotFoundException.java
- product/src/main/java/com/yas/product/utils/Constants.java
- product/src/main/java/com/yas/product/utils/MessagesUtils.java
- product/src/main/resources/messages/messages.properties
I just config [messages.properties] for "product" only.
Should I apply it for other projects (cart, media, ....)?
> issue-211: config messages.properties

- storefront/package-lock.json
- storefront/package.json
- storefront/pages/products/[slug].tsx
add notification when use click 'add to cart' button
> add notification by react-toastify

- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/viewmodel/ProductDetailGetVm.java
- storefront/modules/catalog/models/ProductDetail.ts
- storefront/pages/products/[slug].tsx
- storefront/styles/productDetail.css
1. Change tab title
2. Show the image of a product
4. View the image clearly
> Add view image of product

- storefront/modules/cart/services/CartService.ts
- storefront/pages/cart/index.tsx
> fetch cart ui

- storefront-bff/pom.xml
- storefront-bff/src/main/java/com/yas/storefrontbff/config/ServiceUrlConfig.java
- Similar to upgrade backoffice-bff.
- Remove @ContructorBingding.
> [storefront-bff] upgrade spring boot to v3

- product/src/main/java/com/yas/product/validation/PriceValidator.java
- product/src/main/java/com/yas/product/validation/ValidateProductPrice.java
- product/src/main/java/com/yas/product/viewmodel/ProductPostVm.java
- product/src/main/java/com/yas/product/viewmodel/ProductPutVm.java
Custom Annotation for validate product's price must greater than 0.
> Backend validation for product

- backoffice/pages/catalog/products/index.tsx
- product/src/main/java/com/yas/product/repository/ProductRepository.java
- product/src/main/java/com/yas/product/service/MediaService.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/viewmodel/ProductDetailVm.java
- product/src/main/java/com/yas/product/viewmodel/ProductPutVm.java
- product/src/test/java/com/yas/product/service/ProductServiceTest.java
I found that when we searching product in Backoffice we had to click on 'search icon', i think it's very inconvenient so i added 'debounce searching' for it.
+ Refactor and optimize product service.
> Backoffice/add 'Debounce search' AND Product/Optimize and refactor code

- product/src/main/java/com/yas/product/controller/CategoryController.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/utils/Constants.java
- product/src/main/resources/messages/messages.properties
- product/src/test/java/com/yas/product/service/ProductServiceTest.java
- storefront/common/components/Layout.tsx
- storefront/common/items/ProductItems.tsx
- storefront/pages/index.tsx
- storefront/pages/products/[slug].tsx
- storefront/pages/products/index.tsx
- storefront/styles/globals.css
- storefront/styles/productList.module.css
Add Product Listing (only Show products and categories for now) for StoreFront
> storefront/add Product List FE

- cart/pom.xml
- customer/pom.xml
- media/pom.xml
- product/pom.xml
- product/src/main/resources/application.properties
update springdoc at services:
- cart
- product
- customer
- media
> chore: update version springdoc suitable with sping boot 3

- docker-compose.yml
register rating service in docker-compose.yml file
> register rating service in container swagger-ui

- rating/src/main/java/com/yas/rating/model/Rating.java
- rating/src/test/java/com/yas/rating/config/SecurityConfig.java
- rating/src/test/java/com/yas/rating/model/RatingTest.java
- rating/src/test/java/com/yas/rating/service/RatingServiceTest.java
add testing for rating service
> testing for rating service

- backoffice/common/components/AuthenticationInfo.tsx
- backoffice/common/components/Layout.tsx
- product/src/main/java/com/yas/product/controller/ProductController.java
- product/src/main/java/com/yas/product/repository/ProductRepository.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/viewmodel/ProductsGetVm.java
- storefront/common/components/AuthenticationInfo.tsx
- storefront/common/components/Layout.tsx
- storefront/common/items/ProductItems.tsx
- storefront/modules/catalog/models/ProductFeature.ts
- storefront/modules/catalog/models/ProductThumbnail.ts
- storefront/modules/catalog/services/ProductService.ts
- storefront/pages/cart/index.tsx
- storefront/pages/index.tsx
- storefront/pages/products/[slug].tsx
- storefront/pages/products/index.tsx
- storefront/styles/productList.module.css
- storefront/utils/concatQueryString.ts
- storefront/utils/formatPrice.ts
- storefront/utils/useDebounce.ts
> feat: add BE and FE integrate fillter product list by params

- backoffice/pages/catalog/categories/index.tsx
Hi @khanhtrand @thiennn  ,
Thanks!
> #293 Categories should reuse common confirmation component

- backoffice/pages/catalog/brands/index.tsx
- backoffice/pages/catalog/product-attribute-groups/index.tsx
- backoffice/pages/catalog/product-attributes/index.tsx
- backoffice/pages/catalog/product-options/index.tsx
- backoffice/pages/catalog/products/index.tsx
Hi @khanhtrand @thiennn ,
Thanks!
> #292 Close Confirmation Popup After Delete Successfully for all pages

- rating/src/main/java/com/yas/rating/controller/RatingController.java
- storefront/modules/catalog/models/Rating.ts
- storefront/modules/catalog/models/RatingPost.ts
- storefront/modules/catalog/services/RatingService.ts
- storefront/package-lock.json
- storefront/package.json
- storefront/pages/products/[slug].tsx
- storefront/styles/productDetail.css
We now can add a review for product
NOTE: Every one can post a review for now,  **WILL UPDATE TO** user can post a review when they have bought that product before   **WHEN ORDER SERVICE IS COMPLETED**
> add Post Rating section for product detail page

- storefront/modules/catalog/components/DetailHeader.tsx
- storefront/modules/catalog/components/ProductDetails.tsx
- storefront/modules/catalog/components/index.ts
- storefront/pages/products/[slug].tsx
- storefront/styles/productDetail.css
Here is my result:
Please, help me to review this PR.
Thanks!
> #304 - Optimize product detail page

- backoffice/modules/catalog/components/BrandGeneralInformation.tsx
- backoffice/modules/catalog/constants/validationPattern.ts
- backoffice/modules/catalog/services/BrandService.ts
- backoffice/pages/catalog/brands/[id]/edit.tsx
- backoffice/pages/catalog/brands/create.tsx
Hi,
I have been updated UI and function.
> #297 update brand pages and apply slug pattern

- cart/src/main/java/com/yas/cart/config/CorsConfig.java
- customer/src/main/java/com/yas/customer/config/CorsConfig.java
- media/src/main/java/com/yas/media/config/CorsConfig.java
- product/src/main/java/com/yas/product/config/CorsConfig.java
- rating/src/main/java/com/yas/rating/config/CorsConfig.java
Fix typo corsConfigurer() -> corsConfigure()
> #321 fix corsConfigurer() -> corsConfigure()

- cart/src/main/java/com/yas/cart/config/DatabaseAutoConfig.java
- cart/src/main/java/com/yas/cart/listener/CustomAuditingEntityListener.java
- cart/src/main/java/com/yas/cart/model/AbstractAuditEntity.java
- cart/src/main/java/com/yas/cart/service/CartService.java
- product/src/main/java/com/yas/product/config/DatabaseAutoConfig.java
- product/src/main/java/com/yas/product/controller/CategoryController.java
- product/src/main/java/com/yas/product/controller/ProductAttributeController.java
- product/src/main/java/com/yas/product/controller/ProductOptionController.java
- product/src/main/java/com/yas/product/listener/CustomAuditingEntityListener.java
- product/src/main/java/com/yas/product/model/AbstractAuditEntity.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/test/java/com/yas/product/service/ProductServiceTest.java
- rating/src/main/java/com/yas/rating/config/DatabaseAutoConfig.java
- rating/src/main/java/com/yas/rating/listener/CustomAuditingEntityListener.java
- rating/src/main/java/com/yas/rating/model/AbstractAuditEntity.java
- rating/src/main/java/com/yas/rating/service/RatingService.java
- rating/src/test/java/com/yas/rating/service/RatingServiceTest.java
Hi a @thiennn , @khanhtrand
Please help me review this PR
Thank you
> 322 auto set createdby lastmodifiedby

- docker-compose.yml
- storefront/pages/products/[slug].tsx
- Fix cant post rating by add domain name customer service into docker_compose file.- 
- Update error message
> fix can post rating

- backoffice/modules/catalog/components/ProductImage.tsx
- backoffice/modules/catalog/services/MediaService.ts
- backoffice/modules/catalog/services/ProductService.ts
- backoffice/pages/catalog/products/create.tsx
- backoffice/styles/ProductImage.module.css
- media/src/main/java/com/yas/media/controller/MediaController.java
- media/src/main/java/com/yas/media/exception/ControllerAdvisor.java
- media/src/main/java/com/yas/media/exception/NotFoundException.java
- media/src/main/java/com/yas/media/exception/UnsupportedMediaTypeException.java
- media/src/main/java/com/yas/media/service/MediaService.java
- media/src/main/java/com/yas/media/service/MediaServiceImpl.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductPostVm.java
#400 - Upload image immediately when choosing a thumbnail and images
Here is result
> #400 - Upload image immediately when choosing a thumbnail and images

- backoffice/common/components/ToastContext.tsx
- backoffice/constants/Common.ts
- backoffice/pages/catalog/product-attribute-groups/index.tsx
- product/src/main/java/com/yas/product/controller/ProductAttributeGroupController.java
- product/src/main/java/com/yas/product/exception/ApiExceptionHandler.java
- product/src/main/java/com/yas/product/utils/Constants.java
Hi, please help me review this MR.
> #384 handle internal server error when delete product attribute group have violated constraints

- backoffice/modules/catalog/components/ProductAttributeGroupGeneralInformation.tsx
- backoffice/modules/catalog/services/ProductAttributeGroupService.ts
- backoffice/pages/catalog/product-attribute-groups/[id]/edit.tsx
- backoffice/pages/catalog/product-attribute-groups/create.tsx
Hi, please help me rv this MR.
> #315 enhance minor ui product attribute group pages

- product/src/main/java/com/yas/product/model/Product.java
- product/src/main/java/com/yas/product/service/ProductService.java
#243 
Please help me review this PR, many thanks.
> Add missing logic

- identity/realm-export.json
- identity/themes/yas/login/login.ftl
- identity/themes/yas/login/resources/css/login.css
- Add default login theme is "yas" theme in realm-export
- Add register Button
> add register button

- backoffice/asset/data/sidebar.tsx
- backoffice/common/components/Layout.tsx
- backoffice/modules/catalog/models/Rating.ts
- backoffice/modules/catalog/services/RatingService.ts
- backoffice/pages/reviews/index.tsx
- backoffice/utils/concatQueryString.ts
- rating/src/main/java/com/yas/rating/controller/RatingController.java
Add Product reviews page, 
i will handle search bar and delete button in the next PR
> #463 [Backoffice] add product reviews page

- product/src/main/java/com/yas/product/controller/ProductOptionController.java
- product/src/main/java/com/yas/product/repository/ProductOptionRepository.java
- product/src/main/java/com/yas/product/service/ProductOptionService.java
- product/src/test/java/com/yas/product/controller/ProductOptionControllerTest.java
Hi all, please help me review this PR
> #424 check existed name for product option

- backoffice/modules/catalog/services/RatingService.ts
- backoffice/pages/reviews/index.tsx
- rating/src/main/java/com/yas/rating/controller/RatingController.java
- rating/src/main/java/com/yas/rating/repository/RatingRepository.java
- rating/src/main/java/com/yas/rating/service/RatingService.java
- rating/src/main/java/com/yas/rating/utils/Constants.java
- rating/src/main/java/com/yas/rating/viewmodel/ResponeStatusVm.java
- rating/src/main/resources/messages/messages.properties
- handle search product
- handle search rating by customer name
- handle delete rating
> handle search and delete in reviews page

- backoffice/modules/catalog/components/ChooseImages.tsx
- backoffice/modules/catalog/components/ChooseThumbnail.tsx
- backoffice/modules/catalog/components/ProductVariant.tsx
- backoffice/styles/ChooseImage.module.css
I just adjusted some UIs that let user understand fields SKU and GTIN are required.
Please, help me review this PR. Thanks.
> #486 - SKU and GTIN should be optional

- cart/src/main/java/com/yas/cart/model/CartItem.java
- cart/src/main/java/com/yas/cart/service/CartService.java
- cart/src/main/java/com/yas/cart/viewmodel/CartItemVm.java
- cart/src/test/java/com/yas/cart/service/CartServiceTest.java
- product/src/main/java/com/yas/product/repository/ProductOptionCombinationRepository.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductVariationGetVm.java
- product/src/test/java/com/yas/product/service/ProductServiceTest.java
- storefront/modules/cart/models/AddToCartModel.ts
- storefront/modules/catalog/components/ProductDetails.tsx
- storefront/modules/catalog/models/ProductVariation.ts
- storefront/pages/products/[slug].tsx
- storefront/styles/productDetail.css
I has finished implement issues #485 and #366,
Please help me review this PR, thank you.
> #485 Product detail with variants and Add to cart with Variants

- order/src/main/java/com/yas/order/model/AbstractAuditEntity.java
- order/src/main/java/com/yas/order/model/Order.java
- order/src/main/java/com/yas/order/model/OrderDetail.java
- order/src/main/java/com/yas/order/model/OrderItem.java
- order/src/main/java/com/yas/order/model/enumeration/EDeliveryMethod.java
- order/src/main/java/com/yas/order/model/enumeration/EDeliveryStatus.java
- order/src/main/java/com/yas/order/model/enumeration/EPaymentMethod.java
create model for order service
> create model for order service

- order/src/main/resources/db/changelog/ddl/changelog-0001.sql
Fix syntax in file changelog.sql
>  fix-liqui-orderservice

- backoffice/common/items/TextEditor.tsx
- backoffice/modules/catalog/components/ProductGeneralInformation.tsx
- backoffice/package-lock.json
- backoffice/package.json
- backoffice/pages/_app.tsx
- backoffice/styles/TextEditor.css
- storefront/modules/catalog/components/ProductDetails.tsx
- storefront/pages/products/[slug].tsx
I just applied a simple text editor using react-quill for description and specification fields in create/update product at backoffice.
> #285 Apply text editor for create/update product page

- storefront/common/components/ImageWithFallback.tsx
- storefront/common/components/ProductImageGallery.tsx
> #514 - Fix failed to load image even though product has images

- backoffice/pages/system/countries/[id]/edit.tsx
- backoffice/pages/system/countries/create.tsx
- backoffice/pages/system/countries/index.tsx
- backoffice/pages/system/state-or-provinces/[id]/edit.tsx
- backoffice/pages/system/state-or-provinces/create.tsx
- backoffice/pages/system/state-or-provinces/index.tsx
- backoffice/tsconfig.json
- location/src/main/java/com/yas/location/service/CountryService.java
- location/src/main/java/com/yas/location/service/StateOrProvinceService.java
> #536 Create Alias for importing path

- identity/themes/yas/login/login.ftl
- identity/themes/yas/login/register.ftl
- identity/themes/yas/login/resources/css/login.css
> #542 - custom register page

- backoffice/modules/rating/components/RatingSearch.tsx
- backoffice/modules/rating/models/RatingSearchForm.ts
- backoffice/modules/rating/services/RatingService.ts
- backoffice/package-lock.json
- backoffice/package.json
- backoffice/pages/reviews/index.tsx
- rating/src/main/java/com/yas/rating/controller/RatingController.java
- rating/src/main/java/com/yas/rating/service/RatingService.java
- rating/src/main/resources/db/changelog/db.changelog-master.yaml
Handle function Search in product reviews page
> handle func search in product reviews

- order/src/main/java/com/yas/order/controller/OrderController.java
- order/src/main/java/com/yas/order/model/Order.java
- order/src/main/java/com/yas/order/model/OrderItem.java
- order/src/main/java/com/yas/order/repository/OrderItemRepository.java
- order/src/main/java/com/yas/order/service/CustomerService.java
- order/src/main/java/com/yas/order/service/OrderService.java
- order/src/main/java/com/yas/order/viewmodel/OrderItemPostVm.java
- order/src/main/java/com/yas/order/viewmodel/OrderItemVm.java
- order/src/main/java/com/yas/order/viewmodel/OrderPostVm.java
- order/src/main/java/com/yas/order/viewmodel/OrderVm.java
- order/src/main/resources/application.properties
- order/src/main/resources/db/changelog/ddl/changelog-0002.sql
- rating/src/main/java/com/yas/rating/controller/RatingController.java
> create first api for order service

- backoffice/modules/catalog/components/CategoryMapping.tsx
- backoffice/modules/catalog/models/Category.ts
- backoffice/pages/catalog/categories/create.tsx
- backoffice/tsconfig.json
Please help me review this PR. Thanks.
> #552 fix click create category fail even though slug is typed

- order/src/main/resources/db/changelog/ddl/changelog-0002.sql
> [liqui-base] add missing column in order service

- docker-compose.yml
fix FATAL: sorry, too many clients already
> increase the postgres max connection to 500

- backoffice/modules/catalog/services/ProductService.ts
- product/src/main/java/com/yas/product/controller/ProductController.java
- storefront/modules/catalog/components/ProductDetails.tsx
- storefront/modules/catalog/services/ProductService.ts
> #597 - Hot fix cannot select variation in product detail page

- product/src/main/resources/db/changelog/data/changelog-0003-product.sql
> Add data to field isActive of product variant liquibase

- storefront/common/components/ProfileLayout.tsx
- storefront/pages/address/[id]/edit.tsx
- storefront/pages/address/create.tsx
- storefront/pages/address/index.tsx
- storefront/pages/profile/index.tsx
- storefront/styles/globals.css
> [Storefront] Add profile layout

- inventory/src/main/java/com/yas/inventory/service/ProductService.java
- inventory/src/main/java/com/yas/inventory/viewmodel/product/ProductQuantityPostVm.java
- product/src/main/java/com/yas/product/controller/ProductController.java
- product/src/main/java/com/yas/product/model/Product.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductQuantityPostVm.java
- product/src/main/resources/db/changelog/ddl/changelog-0008.sql
Hi everyone,
Plz help me to review this PR
Thanks!
> Update  quantity for products when the adjustedQuantity is updated in stock

- .github/workflows/storefront-ci.yaml
- cart/src/main/java/com/yas/cart/controller/CartController.java
- cart/src/main/java/com/yas/cart/service/CartService.java
- storefront/common/components/AuthenticationInfo.tsx
- storefront/common/components/common/Header.tsx
- storefront/context/CartContext.tsx
- storefront/modules/cart/services/CartService.ts
- storefront/modules/catalog/components/ProductDetails.tsx
- storefront/pages/_app.tsx
- storefront/pages/cart/index.tsx
The previous solution for updating items number in cart icon is using EventSource and WebFlux to send a request to server each 1 second.
I think this feature doesn't need to update in real time, so I use ContextAPI for global state and fetch new number of items in cart when user operates with cart.
> #562 Fix count cart item number is not working

- docker-compose.yml
- order/src/main/java/com/yas/order/config/ServiceUrlConfig.java
- order/src/main/java/com/yas/order/service/TaxService.java
- order/src/main/resources/application.properties
- product/src/main/java/com/yas/product/model/Product.java
- product/src/main/resources/db/changelog/ddl/changelog-0008.sql
- tax/src/main/java/com/yas/tax/controller/TaxRateController.java
- tax/src/main/java/com/yas/tax/repository/TaxRateRepository.java
- tax/src/main/java/com/yas/tax/service/TaxRateService.java
Hi everyone,
Plz help me to review this PR,
Add column for product
API get tax rate
Create WS interface
Thanks!
> Update data model and API for calculate tax percent by address

- inventory/src/main/java/com/yas/inventory/service/StockService.java
- inventory/src/main/java/com/yas/inventory/viewmodel/product/ProductQuantityPostVm.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductQuantityPostVm.java
- product/src/main/resources/db/changelog/ddl/changelog-0008.sql
> Integrate API update quantity for product

- backoffice/modules/catalog/components/ProductGeneralInformation.tsx
- backoffice/modules/catalog/models/FormProduct.ts
- backoffice/modules/catalog/models/Product.ts
- backoffice/modules/catalog/models/ProductPayload.ts
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductDetailVm.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductListVm.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductPostVm.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductPutVm.java
- product/src/test/java/com/yas/product/service/ProductServiceTest.java
> Apply tax class for create or update product

- .env
- README.md
- docker-compose.o11y.yml
- docker-compose.search.yml
- docker-compose.yml
- nginx/templates/default.conf.template
I just break the old docker-compose.yml file into multiple files such as:
docker-compose.yml for core services
docker-compose.search.yml for elastic search-related services
docker-compose.o11y.yml for observability-related services
> Seperate docker-compose.yml file

- search/src/main/java/com/yas/search/constant/document_fields/ProductField.java
- search/src/main/java/com/yas/search/controller/ProductController.java
- search/src/main/java/com/yas/search/document/Product.java
- search/src/main/java/com/yas/search/service/ProductService.java
- storefront/modules/search/components/SearchFilter.tsx
- storefront/modules/search/components/SearchResultLayout.tsx
- storefront/modules/search/components/SearchSort.tsx
- storefront/modules/search/models/SearchParams.ts
- storefront/modules/search/services/SearchService.ts
- storefront/package-lock.json
- storefront/pages/search/index.tsx
I just updated API search, added parameter brands, and update some logic so users can filter on it.
> #684 Search able to filter products by brand

- backoffice/modules/catalog/components/index.ts
- backoffice/package-lock.json
- backoffice/package.json
- backoffice/pages/catalog/brands/[id]/edit.tsx
- backoffice/pages/catalog/brands/index.tsx
- backoffice/pages/catalog/product-attribute-groups/[id]/edit.tsx
- backoffice/pages/catalog/product-attribute-groups/index.tsx
- backoffice/pages/catalog/product-attributes/index.tsx
- backoffice/pages/catalog/product-options/[id]/edit.tsx
- backoffice/pages/catalog/product-options/index.tsx
- backoffice/pages/catalog/products/[id]/edit.tsx
- backoffice/pages/catalog/products/[id]/productAttributes.tsx
- backoffice/pages/inventory/warehouse-products/index.tsx
- backoffice/pages/inventory/warehouse-stocks/histories/index.tsx
- backoffice/pages/inventory/warehouse-stocks/index.tsx
- backoffice/pages/inventory/warehouses/[id]/edit.tsx
- backoffice/pages/inventory/warehouses/index.tsx
- backoffice/pages/location/countries/[id]/edit.tsx
- backoffice/pages/location/countries/index.tsx
- backoffice/pages/location/state-or-provinces/[id]/edit.tsx
- backoffice/pages/reviews/index.tsx
- backoffice/pages/tax/tax-classes/[id]/edit.tsx
- backoffice/pages/tax/tax-classes/index.tsx
- backoffice/pages/tax/tax-rates/[id]/edit.tsx
- backoffice/pages/tax/tax-rates/index.tsx
- storefront/package-lock.json
- storefront/package.json
- storefront/pages/checkout/[id].tsx
- storefront/pages/redirect/index.tsx
- storefront/styles/modules/search/SearchFilter.module.css
I just ignore lint warning for the dependency of useEffect when it is empty or vice versa both in backoffice and storefront.
I also add the library `sharp` to storefront because NextJS warning missing Sharp for optimizing images in Production.
I also fix some CSS warning.
> #246 - Resolve warning when build backoffice and storefront

- backoffice/common/components/Layout.tsx
- backoffice/modules/order/components/AddressTable.tsx
- backoffice/modules/order/components/BillingNShippingInfo.tsx
- backoffice/modules/order/components/OrderBriefInfo.tsx
- backoffice/modules/order/components/OrderHistory.tsx
- backoffice/modules/order/components/OrderProductInfo.tsx
- backoffice/modules/order/models/Order.ts
- backoffice/modules/order/services/OrderService.ts
- backoffice/pages/sales/orders/[id]/edit.tsx
- backoffice/pages/sales/orders/index.tsx
Add order detail view in backoffice
https://github.com/nashtech-garage/yas/assets/62151844/7fa029f3-82f7-4666-825c-7eb9aab38847
> Add order detail view in backoffice

- backoffice/asset/data/sidebar.tsx
- backoffice/common/components/Layout.tsx
- backoffice/constants/Common.ts
- backoffice/modules/payment/models/Payment.ts
- backoffice/pages/sales/orders/index.tsx
- backoffice/pages/system/payment-providers/index.tsx
> Add payment provider ui

- product/src/main/java/com/yas/product/controller/ProductTemplateController.java
- product/src/main/java/com/yas/product/model/attribute/ProductAttribute.java
- product/src/main/java/com/yas/product/model/attribute/ProductAttributeTemplate.java
- product/src/main/java/com/yas/product/model/attribute/ProductTemplate.java
- product/src/main/java/com/yas/product/repository/ProductAttributeTemplateRepository.java
- product/src/main/java/com/yas/product/repository/ProductTemplateRepository.java
- product/src/main/java/com/yas/product/service/ProductTemplateService.java
- product/src/main/java/com/yas/product/utils/Constants.java
- product/src/main/java/com/yas/product/viewmodel/productattribute/ProductAttributeVm.java
- product/src/main/java/com/yas/product/viewmodel/producttemplate/ProductAttributeTemplateGetVm.java
- product/src/main/java/com/yas/product/viewmodel/producttemplate/ProductAttributeTemplatePostVm.java
- product/src/main/java/com/yas/product/viewmodel/producttemplate/ProductTemplateGetVm.java
- product/src/main/java/com/yas/product/viewmodel/producttemplate/ProductTemplateListGetVm.java
- product/src/main/java/com/yas/product/viewmodel/producttemplate/ProductTemplatePostVm.java
- product/src/main/java/com/yas/product/viewmodel/producttemplate/ProductTemplateVm.java
> update API handle Product Template

- backoffice/modules/catalog/components/ProductAttribute.tsx
- backoffice/pages/catalog/categories/index.tsx
[screen-capture (1).webm](https://github.com/nashtech-garage/yas/assets/64051785/62ef346a-4c06-4828-9554-e39239a05da6)
> [FE] Integrate product template to create product 

- .github/workflows/cart-ci.yaml
- .github/workflows/order-ci.yaml
- .github/workflows/payment-ci.yaml
- .github/workflows/product-ci.yaml
- .gitignore
- backoffice-bff/pom.xml
- cart/pom.xml
- customer/pom.xml
- inventory/pom.xml
- location/pom.xml
- media/pom.xml
- order/pom.xml
- payment-paypal/pom.xml
- payment/pom.xml
- pom.xml
- product/pom.xml
- promotion/pom.xml
- rating/pom.xml
- saga/pom.xml
- search/pom.xml
- storefront-bff/pom.xml
- tax/pom.xml
Currently, all module are use library and version by itself, this refactor will define the common dependency and plugins version at the parent, all child will be inheritance from it. 
The benefit.
- when we upgrade version (spring-*) all child automatic upgrading
- some behavior when build like: style check, bug check, preprocessor with lombok and struct map will be  automatic apply to child module.
> YAS-0001 maven version management

- payment-paypal/Dockerfile
Fix docker build for payment-paypal
> YAS-0003 fix docker payment-paypal

- cart/Dockerfile
- customer/Dockerfile
- inventory/Dockerfile
- location/Dockerfile
- order/Dockerfile
- payment-paypal/Dockerfile
- payment/Dockerfile
- product/Dockerfile
- promotion/Dockerfile
- rating/Dockerfile
- search/Dockerfile
- tax/Dockerfile
I have Replaced ADD with COPY in Dockerfile
> Replaced ADD with COPY in Dockerfile

- inventory/src/main/java/com/yas/inventory/viewmodel/warehouse/WarehousePostVm.java
- inventory/src/test/java/controller/WarehouseControllerTest.java
- location/src/main/java/com/yas/location/controller/AddressController.java
- location/src/main/java/com/yas/location/viewmodel/address/AddressPostVm.java
- location/src/main/java/com/yas/location/viewmodel/country/CountryPostVm.java
- location/src/main/java/com/yas/location/viewmodel/stateorprovince/StateOrProvincePostVm.java
- location/src/test/java/com/yas/locacation/controller/AddressControllerTest.java
- location/src/test/java/com/yas/locacation/controller/CountryControllerTest.java
- location/src/test/java/com/yas/locacation/controller/StateOrProvinceControllerTest.java
- promotion/src/main/java/com/yas/promotion/viewmodel/PromotionPostVm.java
- promotion/src/test/java/com/yas/promotion/controller/PromotionControllerTest.java
- tax/src/main/java/com/yas/tax/viewmodel/taxclass/TaxClassPostVm.java
- tax/src/main/java/com/yas/tax/viewmodel/taxrate/TaxRatePostVm.java
(cherry picked from commit 2a95f45f1a3d9105ce508149f9e64775d5af193e)
> #757 Validate input param for API and add UT for Controller

- storefront/pages/cart/index.tsx
The "Plus" button to increase the quantity of product in shopping cart not work
> The "Plus" button to increase the quantity of product in shopping cart not work

- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/utils/ProductConverter.java
[Shopping Cart] The product image display incorrectly when a product have multiple variations
> [Shopping Cart] The product image display incorrectly when a product have multiple variations

- backoffice/common/items/ProductModal.tsx
- backoffice/pages/catalog/brands/index.tsx
- backoffice/pages/catalog/categories/[id]/listProduct.tsx
- backoffice/pages/catalog/product-attribute-groups/index.tsx
- backoffice/pages/catalog/product-attributes/index.tsx
- backoffice/pages/catalog/product-options/index.tsx
- backoffice/pages/catalog/product-templates/index.tsx
- backoffice/pages/catalog/products/index.tsx
- backoffice/pages/customers/index.tsx
- backoffice/pages/inventory/warehouses/index.tsx
- backoffice/pages/location/countries/index.tsx
- backoffice/pages/location/state-or-provinces/index.tsx
- backoffice/pages/reviews/index.tsx
- backoffice/pages/sales/orders/index.tsx
- backoffice/pages/tax/tax-classes/index.tsx
- backoffice/pages/tax/tax-rates/index.tsx
- backoffice/pages/webhook/index.tsx
- storefront/modules/home/components/FeaturedProduct.tsx
- storefront/modules/rating/components/RatingList.tsx
- storefront/pages/products/index.tsx
[storefront & backoffice] Incorrect pagination display in case of no found or 1 page.
> [storefront & backoffice] Incorrect pagination display in case of no found or 1 page.

- payment/src/main/java/com/yas/payment/PaymentApplication.java
- payment/src/main/java/com/yas/payment/config/DatabaseAutoConfig.java
- payment/src/main/java/com/yas/payment/config/SecurityConfig.java
- payment/src/main/java/com/yas/payment/config/SwaggerConfig.java
- payment/src/main/java/com/yas/payment/controller/PaymentController.java
- payment/src/main/java/com/yas/payment/exception/ApiExceptionHandler.java
- payment/src/main/java/com/yas/payment/model/AbstractAuditEntity.java
- payment/src/main/java/com/yas/payment/model/Payment.java
- payment/src/main/java/com/yas/payment/model/PaymentProvider.java
- payment/src/main/java/com/yas/payment/model/enumeration/PaymentMethod.java
- payment/src/main/java/com/yas/payment/model/enumeration/PaymentStatus.java
- payment/src/main/java/com/yas/payment/service/OrderService.java
- payment/src/main/java/com/yas/payment/service/PaymentProviderService.java
- payment/src/main/java/com/yas/payment/service/PaymentService.java
- payment/src/main/java/com/yas/payment/utils/Constants.java
- payment/src/main/java/com/yas/payment/utils/MessagesUtils.java
- payment/src/main/java/com/yas/payment/viewmodel/CapturedPayment.java
- payment/src/main/java/com/yas/payment/viewmodel/ErrorVm.java
- payment/src/test/java/com/yas/payment/serivce/PaymentServiceTest.java
#850 Fix Checkstyle Payment Service
> #850 Fix Checkstyle Payment Service

- payment-paypal/src/main/java/com/yas/paymentpaypal/PaymentPaypalApplication.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/config/PaypalConfig.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/config/SecurityConfig.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/config/SwaggerConfig.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/controller/PaypalController.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/exception/ApiExceptionHandler.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/model/PaymentProviderHelper.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/service/PaymentService.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/service/PaypalService.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/utils/AuthenticationUtils.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/utils/Constants.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/utils/MessagesUtils.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/viewmodel/CapturedPaymentVm.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/viewmodel/ErrorVm.java
- payment-paypal/src/main/java/com/yas/paymentpaypal/viewmodel/ResponeStatusVm.java
- payment-paypal/src/test/java/com/yas/paymentpaypal/serivce/PaypalServiceTest.java
#850 Fix Checkstyle Payment Paypal Service
> #850 Fix Checkstyle Payment Paypal Service

- promotion/src/main/java/com/yas/promotion/config/DatabaseAutoConfig.java
- promotion/src/main/java/com/yas/promotion/config/SecurityConfig.java
- promotion/src/main/java/com/yas/promotion/config/SwaggerConfig.java
- promotion/src/main/java/com/yas/promotion/controller/PromotionController.java
- promotion/src/main/java/com/yas/promotion/exception/ApiExceptionHandler.java
- promotion/src/main/java/com/yas/promotion/model/AbstractAuditEntity.java
- promotion/src/main/java/com/yas/promotion/model/Promotion.java
- promotion/src/main/java/com/yas/promotion/repository/PromotionRepository.java
- promotion/src/main/java/com/yas/promotion/service/PromotionService.java
- promotion/src/main/java/com/yas/promotion/utils/Constants.java
- promotion/src/main/java/com/yas/promotion/utils/MessagesUtils.java
- promotion/src/main/java/com/yas/promotion/viewmodel/PromotionDetailVm.java
- promotion/src/main/java/com/yas/promotion/viewmodel/PromotionListVm.java
- promotion/src/main/java/com/yas/promotion/viewmodel/PromotionVm.java
- promotion/src/test/java/com/yas/promotion/controller/PromotionControllerTest.java
- promotion/src/test/java/com/yas/promotion/service/PromotionServiceTest.java
#850 Fix Checkstyle Promotion Service
> #850 Fix Checkstyle Promotion Service

- search/src/main/java/com/yas/search/config/SecurityConfig.java
- search/src/main/java/com/yas/search/config/SwaggerConfig.java
- search/src/main/java/com/yas/search/constant/documentations/ProductField.java
- search/src/main/java/com/yas/search/constant/enums/SortType.java
- search/src/main/java/com/yas/search/consumer/ProductSyncDataConsumer.java
- search/src/main/java/com/yas/search/controller/ProductController.java
- search/src/main/java/com/yas/search/document/Product.java
- search/src/main/java/com/yas/search/exception/ApiExceptionHandler.java
- search/src/main/java/com/yas/search/exception/BadRequestException.java
- search/src/main/java/com/yas/search/exception/DuplicatedException.java
- search/src/main/java/com/yas/search/exception/NotFoundException.java
- search/src/main/java/com/yas/search/service/ProductService.java
- search/src/main/java/com/yas/search/service/ProductSyncDataService.java
- search/src/main/java/com/yas/search/utils/MessagesUtils.java
- search/src/main/java/com/yas/search/viewmodel/ProductEsDetailVm.java
- search/src/main/java/com/yas/search/viewmodel/ProductGetVm.java
- search/src/main/java/com/yas/search/viewmodel/error/ErrorVm.java
#850 Fix Checkstyle Search Service
> #850 Fix Checkstyle Search Service

- tax/src/main/java/com/yas/tax/TaxApplication.java
- tax/src/main/java/com/yas/tax/config/CorsConfig.java
- tax/src/main/java/com/yas/tax/config/DatabaseAutoConfig.java
- tax/src/main/java/com/yas/tax/config/RestClientConfig.java
- tax/src/main/java/com/yas/tax/config/SecurityConfig.java
- tax/src/main/java/com/yas/tax/config/SwaggerConfig.java
- tax/src/main/java/com/yas/tax/controller/TaxClassController.java
- tax/src/main/java/com/yas/tax/controller/TaxRateController.java
- tax/src/main/java/com/yas/tax/exception/ApiExceptionHandler.java
- tax/src/main/java/com/yas/tax/exception/BadRequestException.java
- tax/src/main/java/com/yas/tax/exception/DuplicatedException.java
- tax/src/main/java/com/yas/tax/exception/NotFoundException.java
- tax/src/main/java/com/yas/tax/listener/CustomAuditingEntityListener.java
- tax/src/main/java/com/yas/tax/model/AbstractAuditEntity.java
- tax/src/main/java/com/yas/tax/model/TaxClass.java
- tax/src/main/java/com/yas/tax/model/TaxRate.java
- tax/src/main/java/com/yas/tax/repository/TaxClassRepository.java
- tax/src/main/java/com/yas/tax/repository/TaxRateRepository.java
- tax/src/main/java/com/yas/tax/service/LocationService.java
- tax/src/main/java/com/yas/tax/service/TaxClassService.java
- tax/src/main/java/com/yas/tax/service/TaxRateService.java
- tax/src/main/java/com/yas/tax/utils/MessagesUtils.java
- tax/src/main/java/com/yas/tax/viewmodel/error/ErrorVm.java
- tax/src/main/java/com/yas/tax/viewmodel/location/StateOrProvinceAndCountryGetNameVm.java
- tax/src/main/java/com/yas/tax/viewmodel/taxclass/TaxClassPostVm.java
- tax/src/main/java/com/yas/tax/viewmodel/taxclass/TaxClassVm.java
- tax/src/main/java/com/yas/tax/viewmodel/taxrate/TaxRateGetDetailVm.java
- tax/src/main/java/com/yas/tax/viewmodel/taxrate/TaxRateVm.java
- tax/src/test/java/com/yas/tax/service/TaxServiceTest.java
#850 Fix Checkstyle Tax Module
> #850 Fix Checkstyle Tax Module

- storefront-bff/src/main/java/com/yas/storefrontbff/StorefrontBffApplication.java
- storefront-bff/src/main/java/com/yas/storefrontbff/config/SecurityConfig.java
- storefront-bff/src/main/java/com/yas/storefrontbff/config/ServiceUrlConfig.java
- storefront-bff/src/main/java/com/yas/storefrontbff/viewmodel/GuestUserVm.java
- storefront-bff/src/main/java/com/yas/storefrontbff/viewmodel/TokenResponseVm.java
#850 Fix Checkstyle StorefrontBff Module
> #850 Fix Checkstyle StorefrontBff Module

- backoffice-bff/src/main/java/com/yas/backofficebff/Application.java
- backoffice-bff/src/main/java/com/yas/backofficebff/config/SecurityConfig.java
#850 Fix Checkstyle BackofficeBff Module
> #850 Fix Checkstyle BackofficeBff Module

- backoffice/modules/catalog/components/ProductGeneralInformation.tsx
#827 [Backoffice] Description & Specification Product fields randomly cleared to blank even successfully created
> #827 [Backoffice] Description & Specification Product fields randomly cleared to blank even successfully created

- backoffice/pages/catalog/products/[id]/edit.tsx
#885 [Backoffice] Throw generic error when create/edit product variant and unnecessary redirect to homepage
> #885 [Backoffice] Throw generic error when create/edit product variant and unnecessary redirect to homepage

- backoffice/common/services/ResponseStatusHandlingService.ts
- backoffice/pages/catalog/products/[id]/edit.tsx
> #855 throw generic error

- backoffice/common/services/ResponseStatusHandlingService.ts
- backoffice/modules/catalog/services/ProductAttributeValueService.ts
- backoffice/modules/catalog/services/ProductService.ts
- backoffice/pages/catalog/brands/[id]/edit.tsx
- backoffice/pages/catalog/brands/create.tsx
- backoffice/pages/catalog/categories/[id]/edit.tsx
- backoffice/pages/catalog/categories/create.tsx
- backoffice/pages/catalog/product-attribute-groups/[id]/edit.tsx
- backoffice/pages/catalog/product-attribute-groups/create.tsx
- backoffice/pages/catalog/product-attributes/[id]/edit.tsx
- backoffice/pages/catalog/product-attributes/create.tsx
- backoffice/pages/catalog/product-options/[id]/edit.tsx
- backoffice/pages/catalog/product-options/create.tsx
- backoffice/pages/catalog/product-templates/[id]/edit.tsx
- backoffice/pages/catalog/product-templates/create.tsx
- backoffice/pages/catalog/products/[id]/edit.tsx
#885 [Backoffice] Throw generic error to detail message for all screen
> #885 [Backoffice] Throw generic error to detail message for all screen

- .env
- docker-compose.yml
Add environment variables for tax inclusion and currency. Add those variables in docker-compose file for order, payment, and payment-paypal services
> Add environment variables for tax inclusion and currency

- location/src/main/java/com/yas/location/repository/CountryRepository.java
- location/src/main/java/com/yas/location/service/CountryService.java
- location/src/main/java/com/yas/location/utils/Constants.java
- location/src/main/java/com/yas/location/viewmodel/country/CountryPostVm.java
- location/src/main/resources/messages/messages.properties
- location/src/test/java/com/yas/location/service/CountryServiceTest.java
- Added some check to ensure country name and country code2 is unique (case-insensitive) when create a new country.
- Added some test cases for the new check logic.
> [Location] : Add checking duplicate username and code when create new country (#902 validate create country_

- docs/README.md
> docs: update docs/README.md

- storefront/common/services/ApiClientService.ts
- storefront/modules/profile/services/ProfileService.ts
The error , SyntaxError: Unexpected end of JSON input, occurs when the response.json() method is called on an empty response body. This usually happens when the server responds with a **204 No Content** status or an empty body, but the client still tries to parse it as JSON. So the toast will not be called and appear even though the request is executed successfully.
- **Resolve:** Check if the response body is empty or not and avoid trying to parse it as JSON when it is empty.
> #930 [Customer] Configure toast after update information successfully

- product/src/main/resources/db/changelog/db.changelog-master.yaml
#848 Remove databaseChangeLog invalid
> #848 Remove databaseChangeLog invalid

- rating/src/main/java/com/yas/rating/controller/RatingController.java
Change defaultValue in RequestParam so that createdFrom and createdTo can be properly parsed
> #917 Fix Bug when get Rating

- payment/src/test/java/com/yas/payment/serivce/PaymentProviderServiceTest.java
- payment/src/test/java/com/yas/payment/serivce/PaymentServiceTest.java
- Write unit test for PaymentService and PaymentProviderService
> #920 [Payment] Add unit test

- backoffice/modules/catalog/models/ProductPayload.ts
- product/src/main/java/com/yas/product/exception/ApiExceptionHandler.java
- product/src/main/java/com/yas/product/exception/InternalServerErrorException.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/utils/Constants.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductPostVm.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductPutVm.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductSaveVm.java
- product/src/main/resources/messages/messages.properties
1. Convert product slugs to lowercase on backend and frontend.
2. Updated the logic for the `hasOptions` field to correctly handle and display product variations after creation or update.
> #970 Fix mixed case in product slugs and hidden variations

- tax/src/it/java/com/yas/tax/controller/TaxRateControllerIT.java
- tax/src/main/java/com/yas/tax/model/TaxRate.java
- tax/src/main/java/com/yas/tax/viewmodel/taxrate/TaxRatePostVm.java
- tax/src/main/resources/db/changelog/ddl/changelog-0001.sql
> #972 null state id tax rate

- storefront/modules/country/services/CountryService.ts
- storefront/modules/district/services/DistrictService.tsx
- storefront/modules/stateAndProvince/services/StatesOrProvicesService.tsx
**Reformat for:**
- countryService
- districtService
- stateAndProvinceService
> #993 [Storefront] Reformat storefront service to use apiClientService

- backoffice/modules/catalog/components/CategoryImage.tsx
- backoffice/pages/catalog/categories/[id]/edit.tsx
- product/src/main/java/com/yas/product/repository/ProductImageRepository.java
- product/src/main/java/com/yas/product/service/ProductService.java
- Now able to remove the images when create, update product, category
> [Product] Fix error when remove images when create, update product, category

- search/src/it/resources/application.properties
- search/src/it/resources/logback-spring.xml
- search/src/it/resources/mockito-extensions/org.mockito.plugins.MockMaker
- search/src/it/resources/test-realm.json
- search/src/test/java/com/yas/search/consumer/ProductSyncDataConsumerTest.java
- search/src/test/java/com/yas/search/controller/ProductControllerTest.java
- search/src/test/java/com/yas/search/service/ProductServiceTest.java
- search/src/test/java/com/yas/search/service/ProductSyncDataServiceTest.java
- search/src/test/java/resources/test-realm.json
#1013 [Search] Test for module Search
> #1013 [Search] Test for module Search

- product/src/main/java/com/yas/product/service/ProductService.java
- Product variations can now have images added, removed, or changed.
- The issue where thumbnails were displayed even when they did not exist has been resolved.
> #1027 Fix remove images in product variations

- storefront/modules/address/services/AddressService.tsx
- storefront/modules/customer/services/CustomerService.tsx
- storefront/modules/media/services/MediaService.ts
- addressService
- customerService
- mediaService
> Reformat storefront service to use apiClientService

- pom.xml
#1029 [Test] Exclude unnecessary test directories
> #1029 [Test] Exclude unnecessary test directories

- media/src/main/java/com/yas/media/utils/FileTypeValidator.java
Add validation that ensure file uploaded with real image content inside
> #1025-Media-validation-file-upload

- payment-paypal/src/main/java/com/yas/paymentpaypal/model/PaymentProviderHelper.java
Customer now can checkout with PAYPAL as the payment provider.
> #1035 [Payment-PAYPAL]Configure paypal id on paymentProviderHelper

- payment-paypal/src/main/java/com/yas/paymentpaypal/model/PaymentProviderHelper.java
- storefront/modules/cart/services/CartService.ts
- storefront/modules/order/services/OrderService.ts
- storefront/modules/payment/services/PaymentProviderService.ts
- storefront/modules/paymentPaypal/services/PaymentPaypalService.ts
Using apiClientService for:
- cartService
- orderService
- paymentProviderService
- paymentPaypalService
> #993 [Storefront] Reformat order flow to use api client service

- webhook/src/it/java/com/yas/webhook/controller/WebhookControllerIT.java
- webhook/src/test/java/com/yas/webhook/service/OrderEventServiceTest.java
- webhook/src/test/java/com/yas/webhook/service/ProductEventServiceTest.java
> Add test for webhook to reach 80% coverage

- common-library/pom.xml
> #882 Create a shared project: Fix issue

- backoffice/modules/catalog/models/FormProductTemplate.ts
- backoffice/pages/catalog/product-templates/[id]/edit.tsx
- backoffice/pages/catalog/product-templates/create.tsx
#1051 [BACKOFFICE] [Bugs] Product Templates - Categories - Product attributes tab issues
> #1051 [BACKOFFICE] [Bugs] Product Templates - Categories - Product attributes tab issues

- backoffice/modules/catalog/models/ProductAttributeValuePost.ts
- backoffice/pages/catalog/products/[id]/productAttributes.tsx
- backoffice/pages/catalog/products/create.tsx
**#1070 - [BACKOFFICE] [Bugs] Product Attributes : Can't create & view attributes when create/edit product**
> #1070 - [BACKOFFICE] [Bugs] Product Attributes : Can't create & view attributes when create/edit product

- .gitleaksignore
- customer/src/it/java/com/yas/customer/config/IntegrationTestConfiguration.java
- customer/src/it/resources/application.properties
- customer/src/main/resources/application.properties
- Move `#gitleaks:allow` comments from `application.properties` files in the customer module into the `.gitleaksignore` file
> #1067 Fix gitleaks allow

- search/src/main/resources/logback-spring.xml
- storefront/modules/search/components/SearchFilter.tsx
> [Search] Update search UI with attribute filter

- storefront/common/components/ProductImageGallery.tsx
- storefront/modules/catalog/components/ProductDetails.tsx
- storefront/pages/products/[slug].tsx
#1064 [BACKOFFICE] [Bugs] Product Variations - show images
> #1064 [BACKOFFICE] [Bugs] Product Variations - show images

- docs/developer-guidelines.md
**- Update logger to show elasticsearch query vs result**
> Update developer-guidelines.md for elasticsearch

- storefront/pages/cart/index.tsx
- storefront/styles/cart.css
- Added checkboxes next to each item in the shopping cart, allowing customers to select items they wish to purchase.
- Added a 'Select All' checkbox that is unchecked by default.
> #1083 Allow users to select cart items to checkout

- automation-ui/automation-base/src/main/java/com/yas/automation/ui/form/BaseForm.java
- automation-ui/backoffice/src/test/java/com/yas/automation/ui/form/ProductForm.java
- automation-ui/backoffice/src/test/java/com/yas/automation/ui/pages/ProductPage.java
- automation-ui/backoffice/src/test/java/com/yas/automation/ui/steps/CreateProductSteps.java
- automation-ui/backoffice/src/test/resources/features/createProduct.feature
- automation-ui/storefront/src/test/java/com/yas/automation/ui/form/UserRegisterForm.java
- Add flow edit and delete Product
> #1022 - Automation test

- cart/src/it/java/com/yas/cart/service/CartServiceIT.java
- cart/src/main/java/com/yas/cart/mapper/CartGetDetailMapper.java
- cart/src/main/java/com/yas/cart/model/Cart.java
- cart/src/main/java/com/yas/cart/model/CartItem.java
- cart/src/main/java/com/yas/cart/repository/CartRepository.java
- cart/src/main/java/com/yas/cart/service/CartService.java
- cart/src/test/java/com/yas/cart/util/SecurityContextUtils.java
- common-library/src/main/java/com/yas/commonlibrary/mapper/BaseMapper.java
- common-library/src/main/java/com/yas/commonlibrary/utils/AuthenticationUtils.java
- Adjust the add-to-cart logic in the API endpoint `POST /api/cart/storefront/carts`, updating correspond unit test.
- Optimize the number of query executions during the `POST /api/cart/storefront/carts` process.
- Enable `@DynamicUpdate` for the `CartItem` entity.
- Define `MapStruct` for `Cart` and `CartGetDetailVm`.
> #1037 - The quantity doesn't increase if the same product code

- storefront/modules/catalog/components/ProductDetails.tsx
- storefront/pages/products/[slug].tsx
#1064 [BACKOFFICE] [Bugs] Product Variations - select product variants
> #1064 [BACKOFFICE] [Bugs] Product Variations - select product variants

- product/src/main/java/com/yas/product/controller/ProductOptionCombinationController.java
- product/src/main/java/com/yas/product/controller/ProductOptionValueController.java
- product/src/main/java/com/yas/product/repository/ProductOptionCombinationRepository.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductOptionCombinationGetVm.java
- product/src/test/java/com/yas/product/controller/ProductOptionCombinationControllerTest.java
- storefront/modules/catalog/services/ProductService.ts
#1064 [BACKOFFICE] [Bugs] Product Variations - distinct options
> #1064 [BACKOFFICE] [Bugs] Product Variations - distinct options

- product/src/it/java/com/yas/product/service/ProductServiceIT.java
- product/src/main/java/com/yas/product/repository/ProductRepository.java
- product/src/main/java/com/yas/product/service/ProductService.java
#1086  [BACKOFFICE] [Bugs] Product Attributes - Product List View - Related Product
> #1086 [BACKOFFICE] [Bugs] Product Attributes - Product List View - Related Product

- order/src/it/java/com/yas/order/service/OrderServiceIT.java
- order/src/it/resources/application.properties
- order/src/main/java/com/yas/order/controller/OrderController.java
- order/src/main/java/com/yas/order/repository/OrderRepository.java
- order/src/main/java/com/yas/order/service/OrderService.java
- order/src/test/java/com/yas/order/controller/OrderControllerTest.java
- product/src/it/java/com/yas/product/service/ProductServiceIT.java
- product/src/it/resources/application.properties
- product/src/main/java/com/yas/product/controller/ProductController.java
- product/src/main/java/com/yas/product/repository/ProductRepository.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/test/java/com/yas/product/controller/ProductControllerTest.java
- rating/src/main/java/com/yas/rating/controller/RatingController.java
- rating/src/main/java/com/yas/rating/repository/RatingRepository.java
- rating/src/main/java/com/yas/rating/service/RatingService.java
- rating/src/test/java/com/yas/rating/controller/RatingControllerTest.java
- rating/src/test/java/com/yas/rating/service/RatingServiceTest.java
#1128 [BACKOFFICE] [Bugs] Add some boxes in the homepage of the backoffice
> #1128 [BACKOFFICE] [Bugs] Add some boxes in the homepage of the backoffice

- backoffice/modules/promotion/components/MultipleAutoComplete.tsx
- backoffice/modules/promotion/components/PromotionGeneralInformation.tsx
- backoffice/pages/promotion/manager-promotion/index.tsx
- promotion/src/main/java/com/yas/promotion/service/PromotionService.java
- promotion/src/main/java/com/yas/promotion/viewmodel/PromotionPutVm.java
Fixed the following issues:
1. Check that the start date is less than the end date.
2. Fix checkbox 'Is Active' feature is not working.
3. Fix duplicate options when add/edit promotion
> #1133 - [Promotion] Fix bug duplicate option, validate date, show isActive

- backoffice/modules/catalog/models/Product.ts
- backoffice/modules/catalog/services/ProductService.ts
- backoffice/modules/home/components/LatestItemPanel.tsx
- backoffice/modules/home/components/LatestOrders.tsx
- backoffice/modules/home/components/LatestProducts.tsx
- backoffice/modules/home/components/LatestRatings.tsx
- backoffice/modules/home/components/index.ts
- backoffice/modules/order/services/OrderService.ts
- backoffice/modules/rating/services/RatingService.ts
- backoffice/pages/catalog/products/index.tsx
- backoffice/pages/index.tsx
- backoffice/styles/Layout.module.css
- backoffice/styles/common/grid.css
- backoffice/styles/common/style.css
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductDetailVm.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductListVm.java
- product/src/test/java/com/yas/product/controller/ProductControllerTest.java
#1128 [BACKOFFICE] [Bugs] Add some boxes in the homepage of the backoffice front end
> #1128 [BACKOFFICE] [Bugs] Add some boxes in the homepage of the backoffice front end

- backoffice/modules/catalog/services/ProductService.ts
- backoffice/modules/home/components/LatestOrders.tsx
- backoffice/modules/home/components/LatestProducts.tsx
- backoffice/modules/home/components/LatestRatings.tsx
- backoffice/modules/order/services/OrderService.ts
- backoffice/modules/rating/services/RatingService.ts
#1128 [BACKOFFICE] [Bugs] Fixing for handle exception
> #1128 [BACKOFFICE] [Bugs] Fixing for handle exception

- cart/src/it/java/com/yas/cart/controller/CartItemV2ControllerIT.java
- cart/src/main/java/com/yas/cart/controller/CartItemV2Controller.java
- cart/src/main/java/com/yas/cart/mapper/CartItemV2Mapper.java
- cart/src/main/java/com/yas/cart/repository/CartItemV2Repository.java
- cart/src/main/java/com/yas/cart/service/CartItemV2Service.java
- cart/src/main/java/com/yas/cart/utils/Constants.java
- cart/src/main/java/com/yas/cart/viewmodel/CartItemV2DeleteVm.java
- cart/src/main/resources/messages/messages.properties
- cart/src/test/java/com/yas/cart/controller/CartItemV2ControllerTest.java
- cart/src/test/java/com/yas/cart/service/CartItemV2ServiceTest.java
- common-library/src/main/java/com/yas/commonlibrary/exception/ApiExceptionHandler.java
- Implemented an API to delete all cart items associated with a customer when an order is successfully created
- Implemented an API to delete a single cart item.
The design of these APIs can be found at the following issue: https://github.com/nashtech-garage/yas/issues/1099
> #1099 Implement bulk delete cart items & delete single item APIs

- .env
- backoffice-bff/pom.xml
- backoffice-bff/src/main/resources/application.yaml
- docker-compose.yml
- storefront-bff/pom.xml
- storefront-bff/src/main/resources/application.yaml
> Authentication and session handling in BFF don't work in cluster mode

- storefront/modules/catalog/services/CategoryService.ts
- storefront/modules/catalog/services/ProductService.ts
- storefront/modules/rating/services/RatingService.ts
- storefront/modules/sampledata/services/SampleDataService.ts
- storefront/modules/search/services/SearchService.ts
**- Stars:**
**- Ratings:**
**- Related products:**
**- Featured products:**
**- Product's detail:**
> [Storefront] Reformat apiClientService(Done)

- backoffice/common/items/Input.tsx
- backoffice/modules/catalog/components/ProductGeneralInformation.tsx
- backoffice/package-lock.json
- backoffice/package.json
Evidence attached on Issue #1142
> Issue #1142: format number input

- product/src/it/java/com/yas/product/controller/ProductControllerIT.java
- product/src/main/java/com/yas/product/controller/ProductController.java
- product/src/main/java/com/yas/product/repository/ProductRepository.java
- product/src/main/java/com/yas/product/service/ProductService.java
- product/src/main/java/com/yas/product/utils/Constants.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductCheckoutListVm.java
- product/src/main/java/com/yas/product/viewmodel/product/ProductGetCheckoutListVm.java
- product/src/test/java/com/yas/product/controller/ProductControllerTest.java
- Create GET API in `ProductService` to return product information to `OrderService`
- Add test for new code
- Refactor old code checkstyle in `ProductController`
#1187
> #1105 process to checkout - AC1: Create API to get Product information

- order/src/main/java/com/yas/order/viewmodel/order/OrderPostVm.java
- order/src/main/java/com/yas/order/viewmodel/orderaddress/OrderAddressPostVm.java
- storefront/modules/order/components/CheckOutDetail.tsx
> #1196 fix issue missing payment method and additional validation for other fields

- storefront/modules/cart/components/CartItem.tsx
- storefront/pages/cart/index.tsx
Since the code in the backend is quite extensive, I created this PR specifically for the frontend.
> #1215 - Apply promotion code in cart 

- product/src/it/java/com/yas/product/controller/CategoryControllerIT.java
- product/src/main/java/com/yas/product/controller/CategoryController.java
- product/src/main/java/com/yas/product/repository/CategoryRepository.java
- product/src/main/java/com/yas/product/service/CategoryService.java
> [Storefront] [Category] Create api to get the top n categories

- backoffice/pages/catalog/products/[id]/edit.tsx
- backoffice/pages/catalog/products/create.tsx
**#1201 - [Backoffice] - Unable to add or edit Product Options due to recent bugs that came with the latest code**
> #1201 - [Backoffice] - Unable to add or edit Product Options due to recent bugs that came with the latest code

- search/src/main/java/com/yas/search/service/ProductService.java
- storefront/asset/data/data_header_client.ts
- storefront/common/components/common/Header.tsx
- storefront/modules/catalog/services/CategoryService.ts
> Configure UI for keyword suggestions search

- order/src/it/java/com/yas/order/service/OrderServiceIT.java
- order/src/main/java/com/yas/order/controller/OrderController.java
- order/src/main/java/com/yas/order/mapper/CheckoutMapper.java
- order/src/main/java/com/yas/order/model/Order.java
- order/src/main/java/com/yas/order/model/OrderItem.java
- order/src/main/java/com/yas/order/repository/OrderItemRepository.java
- order/src/main/java/com/yas/order/repository/OrderRepository.java
- order/src/main/java/com/yas/order/service/OrderService.java
- order/src/main/java/com/yas/order/service/PromotionService.java
- order/src/main/java/com/yas/order/specification/OrderSpecification.java
- order/src/main/java/com/yas/order/utils/Constants.java
- order/src/main/java/com/yas/order/viewmodel/checkout/CheckoutPostVm.java
- order/src/main/java/com/yas/order/viewmodel/order/OrderGetVm.java
- order/src/main/java/com/yas/order/viewmodel/order/OrderItemVm.java
- order/src/main/java/com/yas/order/viewmodel/order/OrderVm.java
- order/src/test/java/com/yas/order/controller/OrderControllerTest.java
- order/src/test/java/com/yas/order/specification/OrderSpecificationTest.java
#1249: Refactor entity relationship 1-n
> #1249: Refactor entity relationship 1-n
